pytest:
  stage: test
  image: python:3.13
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m pytest src/test_iris_model.py -v
  artifacts:
    when: always
    reports:
      junit: junit.xml