# .gitlab-ci.yml

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_VERSION: "3.9"

cache:
  paths:
    - .cache/pip
    - venv/

# Запуск тестов
pytest:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  before_script:
    - apt-get update -y && apt-get install -y python3-pip
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m pytest tests/test_main.py -v --cov=main --cov-report=xml
  artifacts:
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - junit.xml
      - coverage.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'